spring:
    application:
        name: collaborative-document
    data:
        elasticsearch:
            client:
                username: elastic
                password: your-strong-password
                ssl:
                    verification-mode: none
            uris: [ "https://localhost:9200" ]
        mongodb:
            uri: mongodb://localhost:27017/docs_db
            auto-index-creation: true
        redis:
            host: localhost
            port: 6379
            password: auth
            database: 0
    #            host: 192.168.80.128
#            port: 6379
#            password: auth
#            database: 10
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            base-url: https://api.deepseek.com
            chat:
                options:
                    temperature: 0.8
                    model: deepseek-chat
            embedding:
                api-key: sk-25b014bfde6947cdacc2fc55e8e0eb27
                base-url: https://dashscope.aliyuncs.com/compatible-mode
                options:
                    model: text-embedding-v4
                    dimensions: 2048
springdoc:
    api-docs:
        enabled: true # 开启OpenApi接口
    swagger-ui:
        enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启

feishu:
    jwt:
        # 设置jwt签名加密时使用的秘钥
        user-secret-key: mySuperSecretKeyThatIsLongEnough123456
        # 设置jwt过期时间
        user-ttl: 7200000000
        # 设置前端传递过来的令牌名称
        user-token-name: Authorization

logging:
    level:
        org.springframework.ai.chat.client.advisor: debug
        com.feishu.ai: DEBUG
